[build]
builder = "nixpacks"

[deploy]
startCommand = "npx serve -s dist -l $PORT --single"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "on_failure"

[env]
NODE_ENV = "production" 